<?php

return [
    'passwords' => [
        'ADMIN_PASSWORD_ADMIN_ESDM_GO_ID' => env('ADMIN_PASSWORD_ADMIN_ESDM_GO_ID'),
        'ADMIN_PASSWORD_INFORMASI_ESDM_GO_ID' => env('ADMIN_PASSWORD_INFORMASI_ESDM_GO_ID'),
        'ADMIN_PASSWORD_PENGADUAN_ESDM_GO_ID' => env('ADMIN_PASSWORD_PENGADUAN_ESDM_GO_ID'),
        'ADMIN_PASSWORD_BANTUAN_ESDM_GO_ID' => env('ADMIN_PASSWORD_BANTUAN_ESDM_GO_ID'),
        'ADMIN_PASSWORD_LAYANAN_ESDM_GO_ID' => env('ADMIN_PASSWORD_LAYANAN_ESDM_GO_ID'),
    ],
];